name: Manual release

on: workflow_dispatch

jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Download lambda artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda
          path: ./lambda_artifact

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          version=$(grep '^version' pyproject.toml | head -n 1 | cut -d '"' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Rename artifact
        run: mv ./lambda_artifact/lambda s3-sync-lambda.zip

      - name: Create GitHub release
        run: |
          gh release create v${{ steps.get_version.outputs.version }} \
            s3-sync-lambda.zip \
            --title "Release v${{ steps.get_version.outputs.version }}" \
            --notes "Automated release via GitHub Actions"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

