name: Manual release

on: workflow_dispatch

jobs:
  release:
    name: Manual release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/workflows/common

      - name: Build the lambda function
        run: ./dev.py build

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          set -euo pipefail
          version=$(grep '^version' pyproject.toml | head -n 1 | cut -d '"' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT
          semverized=semverize $version
          echo "semverized=$semverized" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        run: |
          gh release create v${{ steps.get_version.outputs.semverized }} \
            lambdas/s3-sync-lambda.zip \
            --title "v${{ steps.get_version.outputs.semverized }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

