name: Test infra lint & format check

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.hcl'
      - '**/terragrunt.hcl'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 'latest'

      - name: Set up TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Check formatting
        run: tofu fmt -check -recursive

      - name: Lint with tflint
        run: tflint --recursive

      - name: Validate with Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt
          terragrunt validate-all
